version: '3'
services:
  app-spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8090"
    environment:
      - REDIS_HOST=redis-spring
      - SERVER_PORT=8090
      - INTEGRATION_CLIENT_SALES_URL=http://app-dotnet
  app-dotnet:
    build:
      context: ../ASPNETCore3.1_StackExchange.Redis/APICotacoes
      dockerfile: Dockerfile
    ports:
      - "8030:80"
  redis:
    image: redis
    #command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
  redis-spring:
    image: redis
    #command: redis-server --requirepass Redis2019!
    #ports:
    #  - "6379:6379"
