package com.kaikeventura.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.data.annotation.Id;

import java.io.Serializable;

@DynamoDBTable(tableName = "MeetupChaves")
public class MeetupChaves implements Serializable {

    private static final long serialVersionUID = -4282005207341771716L;

    @Id
    @DynamoDBHashKey(attributeName = "idx_documento")
    @JsonIgnore
    private Integer id;

    @DynamoDBAttribute(attributeName = "idx_sort")
    @JsonProperty("name")
    private String name;

    @DynamoDBAttribute(attributeName = "city_code")
    @JsonProperty("city_code")
    private String cityCode;

    @DynamoDBAttribute(attributeName = "likes_chocolate")
    @JsonProperty("likes_chocolate")
    private Boolean likesChocolate;

    public MeetupChaves() {
    }

    public MeetupChaves(String name, String cityCode, Boolean likesChocolate) {
        this.name = name;
        this.cityCode = cityCode;
        this.likesChocolate = likesChocolate;
    }

    public MeetupChaves(Integer id, String name, String cityCode, Boolean likesChocolate) {
        this.id = id;
        this.name = name;
        this.cityCode = cityCode;
        this.likesChocolate = likesChocolate;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCityCode() {
        return cityCode;
    }

    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    public Boolean getLikesChocolate() {
        return likesChocolate;
    }

    public void setLikesChocolate(Boolean likesChocolate) {
        this.likesChocolate = likesChocolate;
    }
}
