version: '3'
services:
  app-dotnet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8030:80"
  redis:
    image: redis
    #command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"